[settings]
    epochs = 500
    batch_size = 1
    device = "cuda"
    num_workers = 1
    train_tsv_file = "data/train.tsv"
    eval_tsv_file = "data/eval.tsv"
    output_dir = "outputs"
    name = "train"
    ckpt = ""
    early_stop = 30
    conditional = true
    sampling_timesteps = 100
    weight = [0.5, 0.5]

[detail]
    optimizer = "Adam"
    scheduler = "ReduceLROnPlateau"
    lr = 0.001
    weight_decay = 1e-5
    momentum = 0.9 # for SGD
    factor = 0.5
    patience = 5
    min_lr = 1e-6
    step_size = 10 # for StepLR
    in_channels = 3
    base_channels = 64
    transformer_dim = 256
    patch_size = 16
    num_transformer_layers = 4
    num_heads = 8

[diffusion]
    optimizer = "Adam"
    scheduler = "StepLR"
    weight_decay = 0.000
    lr = 0.0001
    momentum = 0.9 # for SGD
    factor = 0.8
    patience = 5
    min_lr = 1e-7
    amsgrad = false
    eps = 0.00000001
    step_size = 50
    beta_schedule = "linear"
    beta_start = 0.0001
    beta_end = 0.02
    num_diffusion_timesteps = 200
    in_channels = 3
    out_ch = 3
    ch = 64
    ch_mult = [1, 2, 3, 4]
    num_res_blocks = 2
    dropout = 0.0
    ema_rate = 0.999
    ema = true
    resamp_with_conv = true

[loss]
    epsilon = 1e-3
    lambda_vgg = 1
    lambda_resnet = 1
