epochs: 100
batch_size: 4
train_tsv_file: "data/train.tsv"
eval_tsv_file: "data/eval.tsv"
learning_rate: 0.001
output_dir: "outputs"

# 模型参数
in_channels: 3
base_channels: 64
transformer_dim: 256
patch_size: 16
num_transformer_layers: 4
num_heads: 8

# 训练参数
weight_decay: 1e-5

